name: nix workflows
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  nix-flake-check:
    name: nix flake check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-23.05
          extra_nix_config: |
            experimental-features = nix-command flakes
            system-features = nixos-test benchmark big-parallel kvm

      - name: Check nix.conf
        run: cat /etc/nix/nix.conf

      - name: nix flake show
        run: |
          nix flake show

      - name: nix flake check
        run: |
          nix flake check

  build-proxmox-image:
    needs: [nix-flake-check]
    name: Build proxmox image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-23.05
          extra_nix_config: |
            experimental-features = nix-command flakes
            system-features = nixos-test benchmark big-parallel kvm

      - name: build proxmox image
        run: nix build '.#proxmox-image'

      - name: list result
        run: ls -al --block-size=M result/

      - name: prepare upload folder
        run: |
          name=$(ls result/vzdump-qemu-nixos-*.vma.zst)
          output=$(basename $name .vma.zst)
          echo "filename=$output" >> $GITHUB_ENV

          mkdir upload
          cp result/vzdump-qemu-nixos-*.vma.zst upload/
          ls -al upload

          mkdir current_version
          echo $output/$(basename $name) > current_version/info.txt

      - name: 📂 Upload files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          protocol: ftps
          local-dir: ./upload/
          server-dir: ./${{ env.filename }}/

      - name: 📂 Upload newest
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          protocol: ftps
          local-dir: ./current_version/
          server-dir: ./current_version/
